#!/usr/bin/env bash

## check for sudo/root
if ! [ $(id -u) = 0 ]; then
  echo "This script must run with sudo, try again..."
  exit 1
fi

# Get the username of the user who invoked sudo
if [ "$SUDO_USER" ]; then
  username="$SUDO_USER"
else
  username="$(whoami)"
fi

# Get the home directory of the user
homedir=$(getent passwd "$username" | cut -d: -f6)

run_custom_desktop() {

	git clone https://github.com/Warcren/qogir-theme.git
	./qogir-theme/install.sh
	./qogir-theme/install.sh --tweaks round

	git clone https://github.com/Warcren/qogir-icon-theme.git
	mkdir -p "$homedir/.icons"
	./qogir-icon-theme/install.sh -d "$homedir/.icons"

	#fonts.zip
	unzip fonts.zip
	mv fonts "$homedir/.local/share/"

	#Setup Ulauncher
	unzip ulauncher-theme-goxir-dark.zip
	mkdir -p "$homedir/.config/ulauncher/user-themes/"
	mv goxir-dark "$homedir/.config/ulauncher/user-themes/"

	#Move Menu Config
	unzip whisker-menu.gtk.css.dark
	mkdir -p "$homedir/.config/gtk-3.0/"
	mv gtk.css "$homedir/.config/gtk-3.0/"
	xfce4-panel -r

	#Install Conky
	unzip conky.zip
	mv conky "$homedir/.config/"

	#Install Picom
	unzip picom.zip
	mkdir -p "$homedir/.config/picom"
	mv picom/picom.desktop "$homedir/.config/autostart"
	mv picom/picom.conf "$homedir/.config/picom"
}

#Custom Desktop
run_custom_desktop
